### ISSUE TITLE
Some paths will exception when passed to LogHelper->FMLLog

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#121]
C:\Users\btric\Documents\Curse\Minecraft\Instances\Magitech Pack (0\config\Woot.cfg

Causes:
java.util.UnknownFormatConversionException: Conversion = ')'
    at java.util.Formatter.checkText(Formatter.java:2579) ~[?:1.8.0_25]
    at java.util.Formatter.parse(Formatter.java:2565) ~[?:1.8.0_25]
    at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_25]
    at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_25]
    at java.lang.String.format(String.java:2927) ~[?:1.8.0_25]
    at net.minecraftforge.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:69) [forge-1.10.2-12.18.2.2166.jar:?]
    at net.minecraftforge.fml.common.FMLLog.log(FMLLog.java:32) [FMLLog.class:?]
    at ipsis.woot.oss.LogHelper.log(LogHelper.java:15) ~[LogHelper.class:?]
    at ipsis.woot.oss.LogHelper.info(LogHelper.java:35) ~[LogHelper.class:?]
    at ipsis.woot.manager.loot.LootTableManager.load(LootTableManager.java:165) ~[LootTableManager.class:?]

Don't know quite why is happens, but it shouldn't.

Repoted by RiceWaffleFox via CurseForge page

**Comment by Ipsis** [comment]
So I think what is happening is the the logging system calls into FMLLog.log which treats the test as the format. 

LogHelper.log(Level, Object)
-> FMLLog.log(MOD, level, String.valueOf(object)
->FMLLog.log(String, lvel, format, ... data)

So if there is anything in the path that can be translated by String.format as an escape sequence, then it is going to fail.

**Comment by Ipsis** [comment]
Escaped the '%' which solves the issue for now.
