### ISSUE TITLE
woot cause game to crash 

### ISSUE THREAD

**Issue by lawfulrocky** [Ipsis/Woot#239]
the mod cash the game to crash while loading here is th crash report https://pastebin.com/UBQXN0f5

**Comment by Ipsis** [comment]
Going from your crash report you are running out of block ids.
ie. when woot tries to register its block it is told that there are no block ids free.

As far as I know once you exceed the 4096 limit you cannot add any more mods to your pack.

Is this a public mod pack?
Was it working before?


net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Woot (Woot)
Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:448)
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:829)
    at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:254)
    at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
    at ipsis.woot.init.ModBlocks.preInit(ModBlocks.java:16)
