### ISSUE TITLE
Crash on server start (second boot)

### ISSUE THREAD

**Issue by Anoyomouse** [Ipsis/Woot#382]
Hi

I'm trying the StoneBlock modpack, and i started the world, stopped it, did some maintenance and then restarted it, and the world is just crashing out.

The crash points to your mod:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Woot (woot)

Caused by: java.lang.IllegalArgumentException: Invalid dimension id 418
        at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[ayn.class:?]
        at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:131) ~[DimensionManager.class:?]
        at ipsis.woot.dimension.WootDimensionManager.init(WootDimensionManager.java:37) ~[WootDimensionManager.class:?]
        at ipsis.woot.proxy.CommonProxy.preInit(CommonProxy.java:36) ~[CommonProxy.class:?]
        at ipsis.Woot.preInit(Woot.java:92) ~[Woot.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
```

Full logs: https://www.dropbox.com/sh/v15zbbbihejf368/AACpQLVv5BUDX3mtp3eWe5Cha?dl=0

I'm not sure what's causing this issue

**Comment by Ipsis** [comment]
It looks like Tartarus (the dimension that Woot creates) was created with a its default of 418.
There is a config option in woot/woot.cfg that can be used to change the dimension id.
[general.tartarusId]

My guess is that there is some sort of conflict with some other mod using id 418 as well.
