### ISSUE TITLE
Learning an Evoker causes a npe

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#432]
`java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.player.ServerPlayerEntity.onNewPotionEffect(ServerPlayerEntity.java:1093) ~[forge-1.15.2-31.2.4_mapped_snapshot_20200514-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.addPotionEffect(LivingEntity.java:783) ~[forge-1.15.2-31.2.4_mapped_snapshot_20200514-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.AbstractRaiderEntity.onDeath(AbstractRaiderEntity.java:161) ~[forge-1.15.2-31.2.4_mapped_snapshot_20200514-1.15.1-recomp.jar:?] {re:classloading}
	at ipsis.woot.simulator.spawning.SpawnController.spawnKill(SpawnController.java:56) ~[main/:?] {re:classloading}
	at ipsis.woot.simulator.tartarus.Cell.run(Cell.java:57) ~[main/:?] {re:classloading}
	at ipsis.woot.simulator.MobSimulator.tick(MobSimulator.java:173) ~[main/:?] {re:classloading}
	at ipsis.woot.setup.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:131) ~[main/:?] {re:classloading`

**Comment by Ipsis** [comment]
It is possible this is an issue raised with Forge.
Fake Player NPE on potion added #6358

**Comment by Ipsis** [comment]
The workaround just now is to edit woot-common.toml to add captureEntity = ["minecraft:evoker"]
to the policy.blacklist section.
When the game is restarted then the factory will detect an invalid controller.
Break the controller and replace the heart.
You can now set a different controller and run the factory again.

**Comment by Ipsis** [comment]
Evoker blacklisted in 1.15.2-1.1.0.1

**Comment by UnfortunateName** [comment]
Vindicator also crashes the game

**Comment by Ipsis** [comment]
I've pushed 1.15.2-1.1.0.2 which should stop the crash.
(Fix is from Darkhax who had the same issue with DarkUtilties).
I'll pull the fix when the main FakePlayer in Forge is updated.
