### ISSUE TITLE
Woot Startup Error | factory_config.json | 1.12.2

### ISSUE THREAD

**Issue by JustZerooo** [Ipsis/Woot#564]
Server Info
```
[14:28:13] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[14:28:13] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_312, running on Linux:amd64:5.4.0-96-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
```

After setup the FTB Revelation Modpack Server i got this issue here.

```log
[14:30:22] [Server thread/ERROR] [woot]: Woot: Could not load factory config from /home/sid_3413746/minecraft_forge_1122_latest/config/woot/factory_config.json
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: com.google.gson.JsonSyntaxException: entitygenerateonly must a string list
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at ipsis.woot.configuration.loaders.FactoryConfigLoader.parseConfig(FactoryConfigLoader.java:77)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at ipsis.woot.configuration.loaders.FactoryConfigLoader.loadConfig(FactoryConfigLoader.java:30)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at ipsis.Woot.init(Woot.java:105)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[14:30:22] [Server thread/INFO] [STDERR]: [ipsis.woot.configuration.loaders.FactoryConfigLoader:loadConfig:34]: 	at java.lang.Thread.run(Thread.java:748)
```

The JSON File itself
```json
{
   "version":1,
   "mobconfigs":[
      {
         "mobName":"minecraft:villager",
         "configs":[
            {
               "tag":"factory_tier",
               "value":3
            }
         ]
      },
      {
         "mobName":"minecraft:wither_skeleton",
         "configs":[
            {
               "tag":"spawn_units",
               "value":40
            },
            {
               "tag":"factory_tier",
               "value":3
            }
         ]
      },
      {
         "mobName":"minecraft:magma_cube",
         "configs":[
            {
               "tag":"factory_tier",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:enderman",
         "configs":[
            {
               "tag":"factory_tier",
               "value":3
            }
         ]
      },
      {
         "mobName":"minecraft:ender_dragon",
         "configs":[
            {
               "tag":"death_xp",
               "value":500
            },
            {
               "tag":"spawn_units",
               "value":500
            },
            {
               "tag":"factory_tier",
               "value":4
            },
            {
               "tag":"spawn_ticks",
               "value":12000
            },
            {
               "tag":"mass_1_param",
               "value":2
            },
            {
               "tag":"mass_2_param",
               "value":3
            },
            {
               "tag":"mass_3_param",
               "value":4
            },
            {
               "tag":"mass_fx",
               "value":2
            }
         ]
      },
      {
         "mobName":"draconicevolution:chaosguardian",
         "configs":[
            {
               "tag":"death_xp",
               "value":5000
            },
            {
               "tag":"spawn_units",
               "value":5000
            },
            {
               "tag":"factory_tier",
               "value":4
            },
            {
               "tag":"spawn_ticks",
               "value":12000
            },
            {
               "tag":"mass_1_param",
               "value":1
            },
            {
               "tag":"mass_2_param",
               "value":1
            },
            {
               "tag":"mass_3_param",
               "value":2
            },
            {
               "tag":"mass_fx",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:wither",
         "configs":[
            {
               "tag":"factory_tier",
               "value":4
            },
            {
               "tag":"spawn_units",
               "value":500
            },
            {
               "tag":"spawn_ticks",
               "value":1200
            },
            {
               "tag":"mass_1_param",
               "value":2
            },
            {
               "tag":"mass_2_param",
               "value":3
            },
            {
               "tag":"mass_3_param",
               "value":4
            },
            {
               "tag":"mass_fx",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:villager_golem",
         "configs":[
            {
               "tag":"factory_tier",
               "value":3
            }
         ]
      },
      {
         "mobName":"minecraft:guardian",
         "configs":[
            {
               "tag":"factory_tier",
               "value":3
            }
         ]
      },
      {
         "mobName":"minecraft:blaze",
         "configs":[
            {
               "tag":"factory_tier",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:witch",
         "configs":[
            {
               "tag":"factory_tier",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:ghast",
         "configs":[
            {
               "tag":"factory_tier",
               "value":2
            }
         ]
      },
      {
         "mobName":"minecraft:zombie_pigman",
         "configs":[
            {
               "tag":"factory_tier",
               "value":2
            }
         ]
      }
   ],
   "entitymodblacklist":[
      "botania"
   ],
   "entityblacklist":[
      "twilightforest:naga",
      "twilightforest:minoshroom",
      "twilightforest:hydra",
      "twilightforest:ur_ghast",
      "twilightforest:yeti_alpha",
      "twilightforest:snow_queen",
      "twilightforest:giant_miner",
      "twilightforest:armored_giant"
   ],
   "entitywhitelist":[
 
   ],
   "itemmodblacklist":[
 
   ],
   "itemblacklist":[
 
   ]
}
```

If there is no official support, a Patchfix would be nice :)

**Comment by Ipsis** [comment]
1.12 is very much unsupported now.
However the problem just seems to be that your file is missing a section.

The end of it should be the following, and your's is missing the "entitygenerateonlylist" section.

```
  "entitywhitelist": [
  ],
  "itemmodblacklist": [
  ],
  "itemblacklist": [
  ],
  "entitygenerateonlylist": [
  ]
```

**Comment by JustZerooo** [comment]
I have this but get this issue? ... to fix this i need to modify the code, i am allowed to recode this ti fix the issue and bring this file in our modpack as fixxed? can i email you to request for permissions todo it?

The new file 
```json
{
    "version": 1,
    "mobconfigs": [
        {
            "mobName": "minecraft:villager",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 3
                }
            ]
        },
        {
            "mobName": "minecraft:wither_skeleton",
            "configs": [
                {
                    "tag": "spawn_units",
                    "value": 40
                },
                {
                    "tag": "factory_tier",
                    "value": 3
                }
            ]
        },
        {
            "mobName": "minecraft:magma_cube",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:enderman",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 3
                }
            ]
        },
        {
            "mobName": "minecraft:ender_dragon",
            "configs": [
                {
                    "tag": "death_xp",
                    "value": 500
                },
                {
                    "tag": "spawn_units",
                    "value": 500
                },
                {
                    "tag": "factory_tier",
                    "value": 4
                },
                {
                    "tag": "spawn_ticks",
                    "value": 12000
                },
                {
                    "tag": "mass_1_param",
                    "value": 2
                },
                {
                    "tag": "mass_2_param",
                    "value": 3
                },
                {
                    "tag": "mass_3_param",
                    "value": 4
                },
                {
                    "tag": "mass_fx",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "draconicevolution:chaosguardian",
            "configs": [
                {
                    "tag": "death_xp",
                    "value": 5000
                },
                {
                    "tag": "spawn_units",
                    "value": 5000
                },
                {
                    "tag": "factory_tier",
                    "value": 4
                },
                {
                    "tag": "spawn_ticks",
                    "value": 12000
                },
                {
                    "tag": "mass_1_param",
                    "value": 1
                },
                {
                    "tag": "mass_2_param",
                    "value": 1
                },
                {
                    "tag": "mass_3_param",
                    "value": 2
                },
                {
                    "tag": "mass_fx",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:wither",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 4
                },
                {
                    "tag": "spawn_units",
                    "value": 500
                },
                {
                    "tag": "spawn_ticks",
                    "value": 1200
                },
                {
                    "tag": "mass_1_param",
                    "value": 2
                },
                {
                    "tag": "mass_2_param",
                    "value": 3
                },
                {
                    "tag": "mass_3_param",
                    "value": 4
                },
                {
                    "tag": "mass_fx",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:villager_golem",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 3
                }
            ]
        },
        {
            "mobName": "minecraft:guardian",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 3
                }
            ]
        },
        {
            "mobName": "minecraft:blaze",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:witch",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:ghast",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 2
                }
            ]
        },
        {
            "mobName": "minecraft:zombie_pigman",
            "configs": [
                {
                    "tag": "factory_tier",
                    "value": 2
                }
            ]
        }
    ],
    "entitymodblacklist": [
        "botania"
    ],
    "entityblacklist": [
        "twilightforest:naga",
        "twilightforest:minoshroom",
        "twilightforest:hydra",
        "twilightforest:ur_ghast",
        "twilightforest:yeti_alpha",
        "twilightforest:snow_queen",
        "twilightforest:giant_miner",
        "twilightforest:armored_giant"
    ],
    "entitygenerateonlylist": [],
    "entitywhitelist": [],
    "itemmodblacklist": [],
    "itemblacklist": []
}
```

**Comment by Ipsis** [comment]
I'm a little confused - which code are you wanting to change and to what?
From a quick read of the code, although it is generating an error, it is handled at the very end of the loading and therefore all the rest of the config is still parsed. The missing section will just be untidy but have no impact.
