### ISSUE TITLE
[1.10.2] Mob Controller with Blaze problem

### ISSUE THREAD

**Issue by kwpugh** [Ipsis/Woot#80]
Forge: 2026
Mod: woot-1.10.2-0.2.3-alpha.jar

Have a fully functional, tier 4 Woot.   Works with various mob controllers, but will not form with a Blaze mob controller.   

Error from console:

18:00:29] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
	at ipsis.woot.tileentity.multiblock.MobFactoryMultiblockLogic.validateFactory(MobFactoryMultiblockLogic.java:116) ~[MobFactoryMultiblockLogic.class:?]
	at ipsis.woot.tileentity.multiblock.MobFactoryMultiblockLogic.validateFactory(MobFactoryMultiblockLogic.java:66) ~[MobFactoryMultiblockLogic.class:?]
	at ipsis.woot.tileentity.TileEntityMobFactory.manualValidate(TileEntityMobFactory.java:265) ~[TileEntityMobFactory.class:?]
	at ipsis.woot.block.BlockMobFactory.func_180639_a(BlockMobFactory.java:122) ~[BlockMobFactory.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]

**Comment by Ipsis** [comment]
Think that is the missing mob message that is causing all that messy outpur. Not sure why blaze are special though. I'll do some testing this evening.

**Comment by Ipsis** [comment]
All the messy output seems to be the use of ChatFormatting instead of TextFormatting.

**Comment by Ipsis** [comment]
The bug is an oversight on my part. The validation code says if a the mob needs a T2 factory, then the factory has to be T2 or T3 ..... I forgot to add T4 to that check.
